"""Oracle initial

Revision ID: 0001_oracle_initial
Revises: 
Create Date: 2025-09-04 16:52:47.878387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_oracle_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel_hierarquico', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('pode_atender_os', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('patrimonio', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Operacional', nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patrimonio')
    )
    op.create_table('formulario_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dados', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('processo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Ativo', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cargo_funcoes',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcao.id'], ),
    sa.PrimaryKeyConstraint('cargo_id', 'funcao_id')
    )
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('tipo_estabelecimento', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('telefone_principal', sa.String(length=20), nullable=True),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('email_contato', sa.String(length=120), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cargo_default_setores',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('cargo_id', 'setor_id')
    )
    op.create_table('celula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cargo_default_celulas',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('celula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.PrimaryKeyConstraint('cargo_id', 'celula_id')
    )
    op.create_table('tipo_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('equipe_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('formulario_vinculado_id', sa.Integer(), nullable=True),
    sa.Column('obrigatorio_preenchimento', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['equipe_responsavel_id'], ['celula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('ramal', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('celula_id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('username')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='rascunho', nullable=False),
    sa.Column('visibility', sa.String(length=50), server_default='celula', nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=True),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('vis_celula_id', sa.Integer(), nullable=True),
    sa.Column('celula_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('arquivos', sa.Text(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vis_celula_id'], ['celula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estrutura', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('celula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), server_default='geral', nullable=False),
    sa.Column('lido', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo_os_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='rascunho', nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atribuido_para_id', sa.Integer(), nullable=True),
    sa.Column('equipe_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('formulario_respostas_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.String(length=10), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('sistema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atribuido_para_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistema.id'], ),
    sa.ForeignKeyConstraint(['tipo_os_id'], ['tipo_os.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuario_extra_celulas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('celula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'celula_id')
    )
    op.create_table('usuario_extra_setores',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'setor_id')
    )
    op.create_table('usuario_funcoes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'funcao_id')
    )
    op.create_table('article_extra_celulas',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('celula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['celula_id'], ['celula.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'celula_id')
    )
    op.create_table('article_extra_usuarios',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'usuario_id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artigo_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('anexo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.String(length=36), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('origem_status', sa.String(length=50), nullable=True),
    sa.Column('destino_status', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico_participante',
    sa.Column('ordem_servico_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('ordem_servico_id', 'usuario_id')
    )
    op.create_table('processo_etapa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processo_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('setor_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('celula_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('formulario_padrao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celula_responsavel_id'], ['celula.id'], ),
    sa.ForeignKeyConstraint(['formulario_padrao_id'], ['formulario.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['setor_responsavel_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artigo_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('subtitulo', sa.String(length=200), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campo_etapa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etapa_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('dica', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['etapa_id'], ['processo_etapa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campo_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('secao_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('subtitulo', sa.String(length=200), nullable=True),
    sa.Column('midia_url', sa.String(length=255), nullable=True),
    sa.Column('obrigatoria', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('permite_multipla_escolha', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('usar_menu_suspenso', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('embaralhar_opcoes', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('tem_opcao_outra', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('ramificacoes', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('condicional', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.ForeignKeyConstraint(['secao_id'], ['secao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo_etapa_article',
    sa.Column('etapa_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['processo_etapa.id'], ),
    sa.PrimaryKeyConstraint('etapa_id', 'article_id')
    )
    op.create_table('processo_etapa_cargo_abre',
    sa.Column('etapa_id', sa.String(length=36), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['processo_etapa.id'], ),
    sa.PrimaryKeyConstraint('etapa_id', 'cargo_id')
    )
    op.create_table('processo_etapa_cargo_atende',
    sa.Column('etapa_id', sa.String(length=36), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['processo_etapa.id'], ),
    sa.PrimaryKeyConstraint('etapa_id', 'cargo_id')
    )
    op.create_table('processo_etapa_tipo_os',
    sa.Column('etapa_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_os_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['processo_etapa.id'], ),
    sa.ForeignKeyConstraint(['tipo_os_id'], ['tipo_os.id'], ),
    sa.PrimaryKeyConstraint('etapa_id', 'tipo_os_id')
    )
    op.create_table('resposta_etapa_os',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ordem_servico_id', sa.String(length=36), nullable=False),
    sa.Column('campo_etapa_id', sa.String(length=36), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('preenchido_por', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campo_etapa_id'], ['campo_etapa.id'], ),
    sa.ForeignKeyConstraint(['preenchido_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    tables = [
        'cargo', 'equipamento', 'formulario_respostas', 'funcao', 'instituicao',
        'sistema', 'estabelecimento', 'setor', 'celula', 'tipo_os',
        'usuario', 'article', 'formulario', 'notification', 'attachment',
        'comentario', 'ordem_servico_comentario', 'ordem_servico_log',
        'revision_request', 'secao', 'campo_formulario'
    ]
    for table in tables:
        op.execute(f"CREATE SEQUENCE {table}_seq START WITH 1 INCREMENT BY 1")
        op.execute(
            f"""
DECLARE
    dummy NUMBER;
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER {table}_before_insert
        BEFORE INSERT ON {table}
        FOR EACH ROW
        BEGIN
            IF :new.id IS NULL THEN
                SELECT {table}_seq.NEXTVAL INTO :new.id FROM dual;
            END IF;
        END;
    ';
END;
"""
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        'cargo', 'equipamento', 'formulario_respostas', 'funcao', 'instituicao',
        'sistema', 'estabelecimento', 'setor', 'celula', 'tipo_os',
        'usuario', 'article', 'formulario', 'notification', 'attachment',
        'comentario', 'ordem_servico_comentario', 'ordem_servico_log',
        'revision_request', 'secao', 'campo_formulario'
    ]
    for table in tables:
        op.execute(f"DROP TRIGGER {table}_before_insert")
        op.execute(f"DROP SEQUENCE {table}_seq")

    op.drop_table('resposta_etapa_os')
    op.drop_table('processo_etapa_tipo_os')
    op.drop_table('processo_etapa_cargo_atende')
    op.drop_table('processo_etapa_cargo_abre')
    op.drop_table('processo_etapa_article')
    op.drop_table('campo_formulario')
    op.drop_table('campo_etapa')
    op.drop_table('secao')
    op.drop_table('revision_request')
    op.drop_table('processo_etapa')
    op.drop_table('ordem_servico_participante')
    op.drop_table('ordem_servico_log')
    op.drop_table('ordem_servico_comentario')
    op.drop_table('comentario')
    op.drop_table('attachment')
    op.drop_table('article_extra_usuarios')
    op.drop_table('article_extra_celulas')
    op.drop_table('usuario_funcoes')
    op.drop_table('usuario_extra_setores')
    op.drop_table('usuario_extra_celulas')
    op.drop_table('ordem_servico')
    op.drop_table('notification')
    op.drop_table('formulario')
    op.drop_table('article')
    op.drop_table('usuario')
    op.drop_table('tipo_os')
    op.drop_table('cargo_default_celulas')
    op.drop_table('celula')
    op.drop_table('cargo_default_setores')
    op.drop_table('setor')
    op.drop_table('estabelecimento')
    op.drop_table('cargo_funcoes')
    op.drop_table('sistema')
    op.drop_table('processo')
    op.drop_table('instituicao')
    op.drop_table('funcao')
    op.drop_table('formulario_respostas')
    op.drop_table('equipamento')
    op.drop_table('cargo')
    # ### end Alembic commands ###
