"""Fase1_estrutura_org_user_CORRIGIDA

Revision ID: 06df0a7c904d
Revises: 4c93f35865c8
Create Date: 2025-05-27 20:16:22.102295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06df0a7c904d'
down_revision = '4c93f35865c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel_hierarquico', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('centro_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centro_custo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.Text(), nullable=True))
        #batch_op.drop_index('ix_attachment_content_fts', postgresql_using='gin')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('matricula', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ramal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_admissao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('telefone_contato', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('centro_custo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('setor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cargo_id', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['cpf'])
        batch_op.create_unique_constraint(None, ['matricula'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'estabelecimento', ['estabelecimento_id'], ['id'])
        batch_op.create_foreign_key(None, 'centro_custo', ['centro_custo_id'], ['id'])
        batch_op.create_foreign_key(None, 'cargo', ['cargo_id'], ['id'])
        batch_op.create_foreign_key(None, 'setor', ['setor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('cargo_id')
        batch_op.drop_column('setor_id')
        batch_op.drop_column('centro_custo_id')
        batch_op.drop_column('estabelecimento_id')
        batch_op.drop_column('ativo')
        batch_op.drop_column('telefone_contato')
        batch_op.drop_column('data_admissao')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('ramal')
        batch_op.drop_column('rg')
        batch_op.drop_column('cpf')
        batch_op.drop_column('matricula')
        batch_op.drop_column('email')

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_content_fts', [sa.literal_column("to_tsvector('portuguese'::regconfig, content)")], unique=False, postgresql_using='gin')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('rascunho', 'pendente', 'em_revisao', 'em_ajuste', 'aprovado', 'rejeitado', name='article_status'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'rascunho'::article_status"))

    op.drop_table('setor')
    op.drop_table('centro_custo')
    op.drop_table('estabelecimento')
    op.drop_table('cargo')
    # ### end Alembic commands ###
