"""Add detailed fields to Estabelecimento and ativo status to org entities

Revision ID: 167292e80389
Revises: 06df0a7c904d
Create Date: 2025-05-29 15:27:54.050471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167292e80389'
down_revision = '06df0a7c904d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('article', schema=None) as batch_op:
    #    batch_op.alter_column('status',
    #           existing_type=sa.VARCHAR(length=10),
    #           type_=sa.Enum('rascunho', 'pendente', 'em_revisao', 'em_ajuste', 'aprovado', 'rejeitado', name='article_status'),
    #           existing_nullable=False,
    #           existing_server_default=sa.text("'rascunho'::article_status"))

    #with op.batch_alter_table('attachment', schema=None) as batch_op:
        #batch_op.drop_index('ix_attachment_content_fts', postgresql_using='gin')

    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('centro_custo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_fantasia', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('razao_social', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('inscricao_estadual', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('inscricao_municipal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tipo_estabelecimento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telefone_principal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefone_secundario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_contato', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('data_abertura', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint(None, ['cnpj'])
        batch_op.drop_column('nome')

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ativo')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('data_abertura')
        batch_op.drop_column('email_contato')
        batch_op.drop_column('telefone_secundario')
        batch_op.drop_column('telefone_principal')
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('tipo_estabelecimento')
        batch_op.drop_column('inscricao_municipal')
        batch_op.drop_column('inscricao_estadual')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('razao_social')
        batch_op.drop_column('nome_fantasia')

    with op.batch_alter_table('centro_custo', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_content_fts', [sa.literal_column("to_tsvector('portuguese'::regconfig, content)")], unique=False, postgresql_using='gin')

    #with op.batch_alter_table('article', schema=None) as batch_op:
    #    batch_op.alter_column('status',
    #           existing_type=sa.Enum('rascunho', 'pendente', 'em_revisao', 'em_ajuste', 'aprovado', 'rejeitado', name='article_status'),
    #           type_=sa.VARCHAR(length=10),
    #           existing_nullable=False,
    #           existing_server_default=sa.text("'rascunho'::article_status"))

    # ### end Alembic commands ###
