"""Add Instituicao and Celula models"

Revision ID: 8f36375399a9
Revises: 167292e80389
Create Date: 2025-05-30 00:00:00
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8f36375399a9'
down_revision = '167292e80389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'instituicao',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )

    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'instituicao', ['instituicao_id'], ['id'])

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'estabelecimento', ['estabelecimento_id'], ['id'])

    op.create_table(
        'celula',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
        sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
        sa.Column('setor_id', sa.Integer(), nullable=True),
        sa.Column('centro_custo_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['centro_custo_id'], ['centro_custo.id']),
        sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id']),
        sa.ForeignKeyConstraint(['setor_id'], ['setor.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celula_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'celula', ['celula_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('celula_id')

    op.drop_table('celula')

    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instituicao_id')

    op.drop_table('instituicao')
    # ### end Alembic commands ###

